services:
  web:
    image: woodcatalogapi:latest
    build:
      context: .
      dockerfile: "/WoodCatalog.API/Dockerfile"
    ports:
      - "5000:8080"
    depends_on:
      - redis
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    links:
      - "redis"

  redis:
    image: redis:alpine
    ports:
      - 6379:6379