services:
  web:
    image: woodcatalogapi:latest
    depends_on:
      - redis_image
    build:
      context: .
      dockerfile: "../WoodCatalog.API/Dockerfile"
    ports:
      - "8088:80"
    links:
      - "redis_image"
    environment:
          - ASPNETCORE_URLS=http://+:80

  redis_image:
    image: redis:alpine
    container_name: redisWoodAPI
    ports:
      - 6379:6379